services:
  - type: web
    name: hali-yikama-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn hali_yikama.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: hali_yikama.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: hali-yikama-db
          property: connectionString
databases:
  - name: hali-yikama-db
    databaseName: haliyikamadb
    user: haliuser
