# Generated by Django 5.2 on 2025-04-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(verbose_name='Alınma Tarihi')),
                ('status', models.CharField(choices=[('received', 'Alındı'), ('being Washed', 'Yıkamada'), ('ready', 'Hazır'), ('cleaned', 'Temizlendi'), ('delivered', 'Teslim Edildi')], default='received', max_length=20, verbose_name='Durum')),
                ('carpet_type', models.CharField(max_length=100, verbose_name='Halı Türü')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Müşteri Adı')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Müşteri E-posta')),
                ('date_delivered', models.DateField(blank=True, null=True, verbose_name='Teslim Tarihi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('takip_kodu', models.CharField(default='DEFAULT_CODE', max_length=100, unique=True, verbose_name='Takip Kodu')),
                ('durum', models.CharField(default='Teslim Alındı', max_length=100, verbose_name='Genel Durum')),
            ],
            options={
                'verbose_name': 'Halı',
                'verbose_name_plural': 'Halılar',
            },
        ),
        migrations.CreateModel(
            name='CustomerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Müşteri Yorumları',
                'verbose_name_plural': 'Müşteri Yorumları',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('order_number', models.CharField(blank=True, editable=False, max_length=12, unique=True)),
                ('takip_kodu', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.carpet')),
            ],
            options={
                'verbose_name': 'Randevular',
                'verbose_name_plural': 'Randevular',
            },
        ),
    ]
