# Generated by Django 5.2 on 2025-04-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='carpet_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
