# Generated by Django 5.2 on 2025-04-21 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_appointment_carpet_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='carpet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.carpet'),
        ),
    ]
