# Generated by Django 5.2 on 2025-04-24 12:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_appointment_carpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='takip_kodu',
            field=models.CharField(blank=True, default='DEFAULT_VALUE', editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='date_received',
            field=models.DateField(auto_now_add=True, verbose_name='Alınma Tarihi'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='takip_kodu',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customercomment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
