# Generated by Django 5.2 on 2025-04-24 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_takip_kodu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Randevu', 'verbose_name_plural': 'Randevular'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='carpet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carpet'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='takip_kodu',
            field=models.CharField(blank=True, editable=False, max_length=100, unique=True),
        ),
    ]
