# Generated by Django 5.2 on 2025-04-24 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appointment_carpet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='carpet',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.carpet'),
        ),
    ]
