# Generated by Django 5.2 on 2025-04-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_appointment_options_alter_appointment_carpet'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Randevular', 'verbose_name_plural': 'Randevular'},
        ),
    ]
