# Generated by Django 5.2 on 2025-04-24 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_at',
            new_name='order_date',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Adres belirtilmedi'),
        ),
        migrations.AddField(
            model_name='order',
            name='carpet_type',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='-', max_length=15),
        ),
    ]
