# Generated by Django 5.2 on 2025-04-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_created_at_order_order_date_order_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carpet_type',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(default='Adres bilgisi yok'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Müşteri', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Hazırlanıyor', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
