# Generated by Django 5.2 on 2025-04-24 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_order_carpet_type_alter_order_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tracking_code',
            new_name='takip_kodu',
        ),
    ]
