# Generated by Django 5.2 on 2025-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_tracking_code_order_takip_kodu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='carpet_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Halı Türü'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='customer_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Müşteri E-posta'),
        ),
        migrations.AlterField(
            model_name='carpet',
            name='customer_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Müşteri Adı'),
        ),
    ]
