# Generated by Django 5.2 on 2025-04-25 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_appointment_carpet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='carpet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carpet'),
        ),
    ]
