# Generated by Django 5.2 on 2025-05-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_appointment_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='status',
            field=models.CharField(choices=[('received', 'Alındı'), ('being-Washed', 'Yıkamada'), ('ready', 'Hazır'), ('cleaned', 'Temizlendi'), ('delivered', 'Teslim Edildi')], default='received', max_length=20, verbose_name='Durum'),
        ),
    ]
