# Generated by Django 5.2 on 2025-04-17 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customercomment',
            options={'verbose_name': 'Müşteri Yorumları', 'verbose_name_plural': 'Müşteri Yorumları'},
        ),
        migrations.AddField(
            model_name='customercomment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
