# Generated by Django 5.2 on 2025-04-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
