# Generated by Django 5.2 on 2025-04-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_delete_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerComment',
        ),
    ]
