# Generated by Django 5.2 on 2025-04-24 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
